services:
  node-app:
    build:
      context: .
      dockerfile: node-app/Dockerfile
    container_name: node-app
    ports:
      - "5001:5001"
    networks:
      - backend
    volumes:
      - ./node-app:/usr/src/app
    working_dir: /usr/src/app

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app
    networks:
      - backend

networks:
  backend:
    driver: bridge
